"use client";

import React from 'react';
import Layout from '@/components/lune/Layout';
import { Users, Gift, Copy, Share2, Award, Zap } from 'lucide-react';
import { motion } from 'framer-motion';

const Referrals = () => {
  const referralStats = [
    { label: 'Total Referrals', value: '42', icon: Users, color: 'text-blue-400' },
    { label: 'Earned Rewards', value: '1,250 LUNE', icon: Gift, color: 'text-purple-400' },
    { label: 'Current Tier', value: 'Gold', icon: Award, color: 'text-yellow-400' },
  ];

  return (
    <Layout>
      <div className="max-w-5xl mx-auto w-full">
        <div className="flex flex-col md:flex-row md:items-center justify-between mb-8 md:mb-12 gap-6">
          <div>
            <h1 className="text-3xl md:text-4xl font-bold tracking-tight mb-2 flex items-center gap-3">
              Referral Program <Zap className="text-yellow-400" />
            </h1>
            <p className="text-gray-500 text-sm md:text-base">Invite your friends to Lune and earn a share of their trading fees.</p>
          </div>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 md:gap-6 mb-8 md:mb-12">
          {referralStats.map((stat, i) => (
            <motion.div
              key={stat.label}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.1 }}
              className="bg-white/5 border border-white/10 rounded-2xl md:rounded-3xl p-6"
            >
              <stat.icon className={`${stat.color} mb-4 w-5 h-5 md:w-6 md:h-6`} />
              <p className="text-[10px] text-gray-500 font-bold uppercase mb-1">{stat.label}</p>
              <p className="text-2xl md:text-3xl font-bold">{stat.value}</p>
            </motion.div>
          ))}
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 md:gap-8">
          <div className="bg-gradient-to-br from-purple-600/20 to-blue-600/20 border border-purple-500/20 rounded-[1.5rem] md:rounded-[2.5rem] p-6 md:p-10">
            <h2 className="text-xl md:text-2xl font-bold mb-4 md:mb-6">Your Referral Link</h2>
            <p className="text-gray-400 mb-6 md:mb-8 leading-relaxed text-sm md:text-base">
              Share this link with your community. You'll earn <span className="text-white font-bold">10% of all trading fees</span> generated by your referrals, paid out instantly in LUNE.
            </p>
            
            <div className="flex gap-2 md:gap-3 mb-6 md:mb-8">
              <div className="flex-1 bg-black/40 border border-white/10 rounded-xl md:rounded-2xl px-3 md:px-4 py-3 md:py-4 font-mono text-[10px] md:text-sm text-purple-400 truncate">
                lune.fi/ref/sollegend_42
              </div>
              <button className="p-3 md:p-4 bg-white text-black rounded-xl md:rounded-2xl hover:bg-gray-200 transition-colors shrink-0">
                <Copy size={20} />
              </button>
            </div>

            <div className="flex gap-4">
              <button className="flex-1 bg-white/10 border border-white/10 h-12 md:h-14 rounded-xl md:rounded-2xl font-bold flex items-center justify-center gap-2 hover:bg-white/20 transition-all text-sm">
                <Share2 size={20} />
                Share on X
              </button>
            </div>
          </div>

          <div className="bg-white/5 border border-white/10 rounded-[1.5rem] md:rounded-[2.5rem] p-6 md:p-10">
            <h2 className="text-xl md:text-2xl font-bold mb-4 md:mb-6">Tier Benefits</h2>
            <div className="space-y-4 md:space-y-6">
              {[
                { tier: 'Bronze', requirement: '0-10 Refs', bonus: '5% Fee Share', active: false },
                { tier: 'Silver', requirement: '11-30 Refs', bonus: '7.5% Fee Share', active: false },
                { tier: 'Gold', requirement: '31-100 Refs', bonus: '10% Fee Share', active: true },
                { tier: 'Diamond', requirement: '100+ Refs', bonus: '15% Fee Share', active: false },
              ].map((tier) => (
                <div key={tier.tier} className={`flex items-center justify-between p-3 md:p-4 rounded-xl md:rounded-2xl border ${tier.active ? 'bg-purple-500/10 border-purple-500/30' : 'bg-white/5 border-white/5'}`}>
                  <div>
                    <p className={`font-bold text-sm md:text-base ${tier.active ? 'text-purple-400' : 'text-white'}`}>{tier.tier}</p>
                    <p className="text-[10px] md:text-xs text-gray-500">{tier.requirement}</p>
                  </div>
                  <div className="text-right">
                    <p className="font-bold text-white text-sm md:text-base">{tier.bonus}</p>
                    {tier.active && <span className="text-[8px] md:text-[10px] font-bold text-purple-400 uppercase">Current Tier</span>}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default Referrals;